// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: terra.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TerraformServiceClient is the client API for TerraformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TerraformServiceClient interface {
	Terra(ctx context.Context, in *TerraRequest, opts ...grpc.CallOption) (*TerraResponse, error)
}

type terraformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerraformServiceClient(cc grpc.ClientConnInterface) TerraformServiceClient {
	return &terraformServiceClient{cc}
}

func (c *terraformServiceClient) Terra(ctx context.Context, in *TerraRequest, opts ...grpc.CallOption) (*TerraResponse, error) {
	out := new(TerraResponse)
	err := c.cc.Invoke(ctx, "/terra.TerraformService/Terra", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerraformServiceServer is the server API for TerraformService service.
// All implementations must embed UnimplementedTerraformServiceServer
// for forward compatibility
type TerraformServiceServer interface {
	Terra(context.Context, *TerraRequest) (*TerraResponse, error)
	mustEmbedUnimplementedTerraformServiceServer()
}

// UnimplementedTerraformServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTerraformServiceServer struct {
}

func (UnimplementedTerraformServiceServer) Terra(context.Context, *TerraRequest) (*TerraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Terra not implemented")
}
func (UnimplementedTerraformServiceServer) mustEmbedUnimplementedTerraformServiceServer() {}

// UnsafeTerraformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerraformServiceServer will
// result in compilation errors.
type UnsafeTerraformServiceServer interface {
	mustEmbedUnimplementedTerraformServiceServer()
}

func RegisterTerraformServiceServer(s grpc.ServiceRegistrar, srv TerraformServiceServer) {
	s.RegisterService(&TerraformService_ServiceDesc, srv)
}

func _TerraformService_Terra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerraformServiceServer).Terra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.TerraformService/Terra",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerraformServiceServer).Terra(ctx, req.(*TerraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerraformService_ServiceDesc is the grpc.ServiceDesc for TerraformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerraformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terra.TerraformService",
	HandlerType: (*TerraformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Terra",
			Handler:    _TerraformService_Terra_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "terra.proto",
}
